[project]
name = "hierarchicalmetaanalysis"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["numpyro", "pymc", "sympy"]

[tool.ruff]
target-version = "py311"
lint = { ignore = ["E731"] }
